
export class FeeDriverDb{
    public static feeDriver = [
        {
            id:1,
            signupFee:50,
            signupCredit:50,
            rideFee:68,
            rideCommission:45
          },
          {
            id:2,
            signupFee:50,
            signupCredit:50,
            rideFee:68,
            rideCommission:45
          },
          {
            id:3,
            signupFee:50,
            signupCredit:50,
            rideFee:68,
            rideCommission:45
          },
          {
            id:4,
            signupFee:50,
            signupCredit:50,
            rideFee:68,
            rideCommission:45
          },
          {
            id:5,
            signupFee:50,
            signupCredit:50,
            rideFee:68,
            rideCommission:45
          }
    ]
}